name: MLOps A1 CI

on:
  push:
    branches:
      - kernelridge

jobs:
  run-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Decision Tree
        run: |
          python train.py

      - name: Run Kernel Ridge
        run: |
          python train2.py
